* Aero Fault Detection

** Introduction
This is an AI/ML project to detect faulty sensors on wind turbines.

** Setup
Everything is set up inside the ```Makefile```. So you have to look inside that file for the options.

First copy the ```.env.sample``` into the ```.env``` and adjust all the environment variables (*DO NOT LEAVE THE DEFAULTS*).

*** Database

The most common options are:

- ```make db_up``` : To start the database

- ```make db_create``` : To create the database tables (after the container was started)

- ```make db_delete``` : To delete the database tables (after the container was created)

- ```make psql``` : To access a psql command inside the DB container

*** Application

- ```make testshell``` : To get a bash shell inside the application container

** Logging Levels

- *DEBUG*: Non mandatory, non relevant logs, that are only useful for developers.

- *INFO*: Relevant logs that can be useful for tracing problems.

- *WARNING*: Errors that can be recovered.

- *ERROR*: Errors that cannot be recovered and could cause potential loss of information.

- *CRITICAL*: Errors that cannot be recovered and cause a loss of information or lead to a program end.

* Data

- T: Temperatura del datalogger
- A: Sensores anal贸gicos
  - KPC
  - Bar贸metro
  - Anem贸metro vertical (si lo tuviera)
    - Veleta
- C: COMMs
  - Anem贸metro
- D: Sensores Digitales
  - Veleta
- Count: Cantidad de medificiones
